name: Download and Upload Office ISO

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download ISO from Microsoft
        run: wget -O OfficeServer.iso "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: html2canvas.min.js
          release_name: "html2canvas.min.js"
          draft: false
          prerelease: false
      
      - name: Upload ISO to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./html2canvas.min.js
          asset_name: html2canvas.min.js
          asset_content_type: application/x-iso9660-image
